version: '3'

services:
  next:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: next
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - PORT=${FRONTEND_PORT}