name: Update Docker Hub README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          set -e  # Fail on any error

          echo "Full curl command:"
          echo "curl -X PUT -H 'Content-Type: application/json' -H 'Authorization: JWT ${DOCKERHUB_TOKEN}' -d '{\"full_description\": \"${{ github.event.repository.description }}\"}' https://hub.docker.com/v2/repositories/${{ github.repository }}/"

          curl -X PUT -H 'Content-Type: application/json' -H 'Authorization: JWT ${DOCKERHUB_TOKEN}' -d '{"full_description": "${{ github.event.repository.description }}"}' https://hub.docker.com/v2/repositories/${{ github.repository }}/ || {
            echo "API call failed with status code $?"
            echo "Response body:"
            cat
            exit 1  # Explicitly fail the job
          }
